/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Usuario;

/**
 *
 * @author IPESMI
 */
public class Principal extends javax.swing.JFrame {
    private Usuario usuarioLogueado;
    /**
     * Creates new form Principal
     */
    public Principal(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        if(this.usuarioLogueado.getNivel().getNivel() == 2)
            mnuItemGUsuarios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuItemGUsuarios = new javax.swing.JMenuItem();
        mnuItemSalir = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mnuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuItemGUsuarios.setText("Gestión de Usuarios");
        mnuArchivo.add(mnuItemGUsuarios);

        mnuItemSalir.setText("Salir");
        mnuArchivo.add(mnuItemSalir);

        barraMenu.add(mnuArchivo);

        mnuOpciones.setText("Opciones");

        mnuItemAcercaDe.setText("Acerca de");
        mnuOpciones.add(mnuItemAcercaDe);

        barraMenu.add(mnuOpciones);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuItemAcercaDe;
    private javax.swing.JMenuItem mnuItemGUsuarios;
    private javax.swing.JMenuItem mnuItemSalir;
    private javax.swing.JMenu mnuOpciones;
    // End of variables declaration//GEN-END:variables
}
